[package]
name = "nutripeer"
version = "0.1.0"
description = "NutriPeer masaustu uygulamasi"
authors = ["NutriPeer"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
